# .github/workflows/publish-pypi.yml
name: "Publish to PyPI"

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Python package with maturin
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: publish
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
